require("configs.settings")
require("plugins")
require("treesitter-config")
require("telescope-config")
-- vim.cmd.colorscheme('nightfox')
vim.cmd.colorscheme('tokyonight')
-- vim.cmd.colorscheme('sobrio')
